unpackaged/main/default/objects/Access_Circuits__c/Access_Circuits__c.object-meta.xml
<CustomObject>
    <description>Access Circuits</description>
    <label>Access Circuit</label>
    <nameField>
        <label>Circuit ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Circuits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Access_Circuits__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Circuits</relationshipLabel>
    <relationshipName>Access_Circuits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Access_Circuits__c/fields/Primary_Carrier_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Carrier_Account_Number__c</fullName>
    <description>Primary carrier account number</description>
    <label>Primary Carrier Account Number</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <infoMessage>If you do not see the branch you expect, then clear the search dialog and click GO. All branches should appear for selection.  Or Manually type Dallas, Austin, San Antonio, Atlanta, or Pittsburgh</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/AcctSeed__Account_Payable__c.object-meta.xml
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Contact__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>An Account Payable can have either the Account (Vendor), Contact or User (Employee) as the Payee.  Only one payee type can be chosen.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Accounts_Payable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Payee_Reference__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payee_Reference__c</fullName>
    <inlineHelpText>Used for Vendor Invoice Number or Expense processing date if account payable is generated from expenses.</inlineHelpText>
    <label>Payee Reference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Only populate if the entire bill is related to one client account.</inlineHelpText>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Accounts_Payable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LookupAccountNumberTest.cls
/*
    07/07/2016  MD@IC  Created (00132544)
*/
@isTest
private class LookupAccountNumberTest{

    @isTest static void tester(){
        //System.assert(false, 'Switch field ids for pre-populate fields');

        AccountingSeedUnitTestUtility.initAccountingSeed();
        Account a = new Account(
            Name = 'Test Inc.',
            Branch__c = AccountingSeedUnittestUtility.variables[0].Id);
        insert a;
        Contact c = new Contact(
            AccountId = a.Id,
            LastName = 'Smith');
        insert c;
        AcctSeed__Account_Payable__c ap = new AcctSeed__Account_Payable__c(
            AcctSeed__Contact__c = c.Id,
            AcctSeed__Payee_Reference__c = '0');
        insert ap;

        Access_Circuits__c ac = new Access_Circuits__c(
            Primary_Carrier_Account_Number__c = '012345',
            Account__c = a.Id);
        insert ac;

        Test.setCurrentPage(new PageReference('/apex/LookupAccountNumber?apid=' + ap.Id + '&retURL=' + ap.Id));
        LookupAccountNumberCtrl ctrl = new LookupAccountNumberCtrl(null);
        System.assert(ctrl.accountPayable != null, 'Ctrl could not find the acct payable');

        List<String> accountNumbers = LookupAccountNumberCtrl.searchAccountNumbers('0');
        System.assertNotEquals(0, accountNumbers.size(), 'No account numbers found');
        System.assertEquals(ac.Primary_Carrier_Account_Number__c, accountNumbers[0], 'Wrong account number returned');

        ctrl.accountNumber = accountNumbers[0];
        ctrl.queryAccessCircuits();
        System.assertEquals(1, ctrl.accessCircuits.size(), 'Wrong number of access circuits returned');

        ctrl.selectedAccessCircuit = ctrl.accessCircuits[0].Id;
        ctrl.selectAccessCircuit();
        ap = [SELECT Id, Client__c FROM AcctSeed__Account_Payable__c WHERE Id = :ap.Id];
        System.assertEquals(ctrl.accessCircuits[0].Account__c, ap.Client__c, 'AP Client not set correctly: ' + ApexPages.getMessages());

        // coverage
        ctrl.newPageOverride = true;
        ctrl.selectAccessCircuit();
        ctrl.skip();
    }

}