unpackaged/main/default/objects/AcctSeed__Accounting_Period__c/AcctSeed__Accounting_Period__c.object-meta.xml
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Billing__c/AcctSeed__Billing__c.object-meta.xml
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of "Open" in order to be selected.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Project_Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>Date the Billing is issued to the customer.</inlineHelpText>
    <label>Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Due_Date2__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Due_Date2__c</fullName>
    <inlineHelpText>The Due Date equals the Billing Date plus the Billing Days Due on the associated Account (Customer) record. Otherwise the Due Date defaults to the Billing Date.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Total__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Total__c</fullName>
    <inlineHelpText>Grand Total for Billing.</inlineHelpText>
    <label>Total</label>
    <summarizedField>AcctSeed__Billing_Line__c.AcctSeed__Total__c</summarizedField>
    <summaryForeignKey>AcctSeed__Billing_Line__c.AcctSeed__Billing__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing__c/fields/Apply_Credit_Memo_to_Billing__c.field-meta.xml
<CustomField>
    <fullName>Apply_Credit_Memo_to_Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apply Credit Memo to Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/AcctSeed__Billing_Line__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing__c</fullName>
    <inlineHelpText>Reference to parent object.</inlineHelpText>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Project_Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Comment__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Comment__c</fullName>
    <inlineHelpText>Comment for display on Billing Line.</inlineHelpText>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <inlineHelpText>Date Product or Service was rendered. Typically used for informational purposes in time and material billings.</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Hours_Units__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Hours_Units__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Quantity for Product Pricing, Hours for Service pricing.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to Salesforce Products. Drives GL Revenue Account if selected and no Revenue GL Account is selected in the Billing Line. Also drives GL Account Variables on transaction line if no Project Task is selected on the Billing Line.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Rate__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Rate__c</fullName>
    <inlineHelpText>Product or Service Rate. Up to 6 decimal places.</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Total__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Total__c</fullName>
    <formula>AcctSeed__Sub_Total__c +  AcctSeed__Tax_Amount2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Hours * Units + Tax</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/CreateCreditMemosController.cls
/*
    10/05/15    SB @ IC    00119955
*/
global class CreateCreditMemosController {
    
    public Id billingId;
    public list<BillingLine> billingLines { get; set; }
    public String sortField { get; set; }
    public static String sField;
    public Boolean sortAsc { get; set; }
    public static Boolean sAsc;
    
    public CreateCreditMemosController(ApexPages.StandardController control) {
        billingId = control.getId();
        sortField = 'Name';
        sortAsc = true;
        retrieveBillingLines();
    }
    
    public void retrieveBillingLines() {
        billingLines = new list<BillingLine>{};
        Decimal totalBillAmount = 0;
        
        for (AcctSeed__Billing_Line__c line : getBillingLines()) {
            billingLines.add(new BillingLine(line));
            if (line.AcctSeed__Total__c != null) totalBillAmount += line.AcctSeed__Total__c;
        }
        
        billingLines.add(new BillingLine(totalBillAmount));
        sortLines();
    }
    
    public AcctSeed__Billing__c getBilling() {
        list<String> fields = new list<String>{};
        for (Schema.SObjectField sobjField : Schema.SObjectType.AcctSeed__Billing__c.fields.getMap().values()) {
            fields.add(sobjField.getDescribe().getName());
        }
        String q = 'SELECT ' + String.join(fields,',') + ' FROM AcctSeed__Billing__c WHERE Id = \''+billingId+'\'';
        return Database.query(q);
    }
    
    public list<AcctSeed__Billing_Line__c> getBillingLines() {
        list<String> fields = new list<String>{};
        for (Schema.SObjectField sobjField : Schema.SObjectType.AcctSeed__Billing_Line__c.fields.getMap().values()) {
            fields.add(sobjField.getDescribe().getName());
        }
        String q = 'SELECT ' + String.join(fields,',') + ',AcctSeed__Product__r.Name FROM AcctSeed__Billing_Line__c WHERE AcctSeed__Billing__c = \''+billingId+'\'';
        return Database.query(q);
    }
    
    public void sortLines() {
        sField = sortField;
        sAsc = sortAsc;
        billingLines.sort();
    }
    
    public void updateSort() {
        String newField = ApexPages.currentPage().getParameters().get('field');
        if (newField == sortField)
            sortAsc = !sortAsc;
        else {
            sortField = newField;
            sortAsc = true;
        }
        sortLines();
    }
    
    public PageReference saveCreditMemos() {
        System.Savepoint save = Database.setSavepoint();
        try {
            Boolean error = false;
            for (BillingLine bl : billingLines) {
                if (bl.selected) {
                    Decimal credit = bl.overrideAmount ? bl.creditAmount : bl.creditQuantity * bl.line.AcctSeed__Rate__c;
                    bl.error = credit > bl.billAmount;
                    error = error || bl.error;
                }
            }
            if (error) return null;
            
            AcctSeed__Billing__c billing = getBilling();
            AcctSeed__Billing__c memo = billing.clone(false,true);
            memo.OwnerId = UserInfo.getUserId();
            //memo.Billing_to_Apply_Credit_Memo__c = billing.Id;
            memo.AcctSeed__Date__c = Date.today();
            memo.AcctSeed__Accounting_Period__c = null;
            memo.AcctSeed__Due_Date2__c = null;
            memo.Apply_Credit_Memo_to_Billing__c = billing.Id;
            insert memo;
            
            list<AcctSeed__Billing_Line__c> memoLines = new list<AcctSeed__Billing_Line__c>{};
            for (BillingLine bl : billingLines) {
                if (!bl.selected) continue;
                
                AcctSeed__Billing_Line__c memoLine = bl.line.clone(false,true);
                memoLine.AcctSeed__Billing__c = memo.Id;
                memoLine.AcctSeed__Hours_Units__c = -1 * bl.creditQuantity;
                memoLine.AcctSeed__Rate__c = bl.overrideAmount ? bl.creditAmount : bl.line.AcctSeed__Rate__c;
                if (String.isNotBlank(bl.description)) memoLine.AcctSeed__Comment__c = bl.description;
                memoLines.add(memoLine);
            }
            insert memoLines;
            
            return new PageReference('/'+memo.Id);
        } catch (Exception e) {
            Database.rollback(save);
            ApexPages.addMessages(e);
            return null;
        }
    }
    
    global class BillingLine implements Comparable {
        public AcctSeed__Billing_Line__c line { get; set; }
        public Boolean selected { get; set; }
        public Decimal billAmount { get; set; }
        public Boolean overrideAmount { get; set; }
        public Decimal creditQuantity { get; set; }
        public Decimal creditAmount { get; set; }
        public String description { get; set; }
        public Boolean error { get; set; }
        
        public BillingLine(AcctSeed__Billing_Line__c bl) {
            line = bl;
            billAmount = line.AcctSeed__Total__c;
            selected = false;
            overrideAmount = false;
            error = false;
        }
        
        public BillingLine(Decimal total) {
            billAmount = total;
            selected = false;
        }
        
        global Integer compareTo(Object compTo) {
            AcctSeed__Billing_Line__c thatLine = ((BillingLine)compTo).line;
            
            if (line == null) return 1;
            else if (thatLine == null) return -1;
            
            if (sField == 'Name') {
                if (line.Name > thatLine.Name) return sAsc ? 1 : -1;
                else if (line.Name < thatLine.Name) return sAsc ? -1 : 1;
            } else if (sField == 'AcctSeed__Hours_Units__c') {
                if (line.AcctSeed__Hours_Units__c > thatLine.AcctSeed__Hours_Units__c) return sAsc ? 1 : -1;
                else if (line.AcctSeed__Hours_Units__c < thatLine.AcctSeed__Hours_Units__c) return sAsc ? -1 : 1;
            } else if (sField == 'AcctSeed__Rate__c') {
                if (line.AcctSeed__Rate__c > thatLine.AcctSeed__Rate__c) return sAsc ? 1 : -1;
                else if (line.AcctSeed__Rate__c < thatLine.AcctSeed__Rate__c) return sAsc ? -1 : 1;
            } else if (sField == 'AcctSeed__Total__c') {
                if (line.AcctSeed__Total__c > thatLine.AcctSeed__Total__c) return sAsc ? 1 : -1;
                else if (line.AcctSeed__Total__c < thatLine.AcctSeed__Total__c) return sAsc ? -1 : 1;
            }
            return 0;
        }
    }
}