unpackaged/main/default/objects/Account/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts (Account Executive)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <infoMessage>If you do not see the branch you expect, then clear the search dialog and click GO. All branches should appear for selection.  Or Manually type Dallas, Austin, San Antonio, Atlanta, or Pittsburgh</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__GL_Account__c/AcctSeed__GL_Account__c.object-meta.xml
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <label>General Ledger Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Ledger Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Active__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Denotes if the GL Account is active. Most filtered lookups to the GL Account object look for an active status.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>Denotes the major grouping for financial reporting.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Balance Sheet</fullName>
                <default>true</default>
                <label>Balance Sheet</label>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/AcctSeed__Recurring_Billing__c.object-meta.xml
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <formula>AcctSeed__Customer__r.Account_Executive__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Executive</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Customer__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Billings</relationshipLabel>
    <relationshipName>Recurring_Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/AcctSeed__Recurring_Billing_Line__c.object-meta.xml
<CustomObject>
    <description>Defines the line level detail of a recurring billing. Aggregation of recurring billing lines constitute a recurring billing.</description>
    <label>Recurring Billing Line</label>
    <nameField>
        <displayFormat>RBL-{00000}</displayFormat>
        <label>Recurring Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <formula>AcctSeed__Recurring_Billing__r.Account_Executive__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Executive</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Recurring_Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Recurring_Billing__c</fullName>
    <label>Recurring Billing</label>
    <referenceTo>AcctSeed__Recurring_Billing__c</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/Lease_Rates__c.object-meta.xml
<CustomObject>
    <label>Lease Rates</label>
    <nameField>
        <label>Lease Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_1__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_1__c</fullName>
    <label>GA Rate 1</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_1_Dollar_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_1_Dollar_Threshold__c</fullName>
    <label>GA Rate 1 Dollar Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_1_Payment_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_1_Payment_Threshold__c</fullName>
    <label>GA Rate 1 Payment Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_2__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_2__c</fullName>
    <label>GA Rate 2</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_2_Dollar_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_2_Dollar_Threshold__c</fullName>
    <label>GA Rate 2 Dollar Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_2_Payment_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_2_Payment_Threshold__c</fullName>
    <label>GA Rate 2 Payment Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_3__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_3__c</fullName>
    <label>GA Rate 3</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_3_Dollar_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_3_Dollar_Threshold__c</fullName>
    <label>GA Rate 3 Dollar Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_3_Payment_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_3_Payment_Threshold__c</fullName>
    <label>GA Rate 3 Payment Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/Rate_Markup__c.field-meta.xml
<CustomField>
    <fullName>Rate_Markup__c</fullName>
    <label>Rate Markup</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/TSB_Rate__c.field-meta.xml
<CustomField>
    <fullName>TSB_Rate__c</fullName>
    <label>TSB Rate</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AnyWare_Term_2016__c.field-meta.xml
<CustomField>
    <fullName>AnyWare_Term_2016__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is a required field. If unsure, set to 60.</description>
    <inlineHelpText>Select the appropriate AnyWare Term/Rate</inlineHelpText>
    <label>AnyWare Term</label>
    <referenceTo>Lease_Rates__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>Account.Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <displayFormat>C-{0}</displayFormat>
    <label>Opportunity/Contract Number</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OPS_Category__c.field-meta.xml
<CustomField>
    <fullName>OPS_Category__c</fullName>
    <label>OPS Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
                <color>#009900</color>
                <label>INSTALLATION</label>
            </value>
            <value>
                <fullName>ICN</fullName>
                <color>#3366FF</color>
                <label>ICN</label>
            </value>
            <value>
                <fullName>MAC</fullName>
                <color>#FF6600</color>
                <label>MAC</label>
            </value>
            <value>
                <fullName>RECAST</fullName>
                <color>#000099</color>
                <label>RECAST</label>
            </value>
            <value>
                <fullName>Post Installation</fullName>
                <color>#000000</color>
                <label>POST INSTALLATION</label>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>Dallas</fullName>
            </value>
            <value>
                <fullName>Houston</fullName>
            </value>
            <value>
                <fullName>Pittsburgh</fullName>
            </value>
            <value>
                <fullName>San Antonio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MergeBillingTest.cls
/*
Test for merge billing extension

02/29/16 BS@IC Created (00127964)
06/02/16 BS@IC Minor fix (132110)
*/

@isTest
public with sharing class MergeBillingTest {
    public static testMethod void test() {
        AccountingSeedUnittestUtility.initAccountingSeed();
        Account acct = new Account(Name = 'MergeBillingTest',Branch__c = AccountingSeedUnittestUtility.variables[0].Id);
        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert acct;
        }

        AcctSeed__GL_Account__c gl = new AcctSeed__GL_Account__c(
            Name = 'MergeBillingTest',
            AcctSeed__Active__c = true,
            AcctSeed__Type__c = 'Revenue'
        );
        insert gl;

        Product2 prod = new Product2(Name = 'MergeBillingTest', IsActive = true, AcctSeed__Revenue_GL_Account__c = gl.Id);
        insert prod;

        PriceBookEntry entry = new PriceBookEntry(
            Product2Id = prod.Id,
            UnitPrice = 42,
            Pricebook2Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        insert entry;

        Lease_Rates__c term = new Lease_Rates__c(Name = 'MergeBillingTest', GA_Rate_1__c = 1, GA_Rate_1_Dollar_Threshold__c = 1, GA_Rate_1_Payment_Threshold__c = 1, GA_Rate_2__c = 1, GA_Rate_2_Dollar_Threshold__c = 1, GA_Rate_2_Payment_Threshold__c = 1, GA_Rate_3__c = 1, GA_Rate_3_Dollar_Threshold__c = 1, GA_Rate_3_Payment_Threshold__c = 1, Rate_Markup__c = 1, TSB_Rate__c = 1);
        insert term;

        Opportunity opp = new Opportunity(Name = 'MergeBillingTest', StageName = 'Prospecting', CloseDate = Date.today(), AccountId = acct.Id, AnyWare_Term_2016__c = term.Id,OPS_Category__c = 'Installation');
        insert opp;
        opp = [SELECT AccountId, Contract_Number__c, Account.Branch__c, Account.Account_Executive__c FROM Opportunity WHERE Id = :opp.Id];

        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Quantity = 42,
            UnitPrice = 10,
            PriceBookEntryId = entry.Id
        );
        insert oli;

        AcctSeed__Recurring_Billing__c billing = new AcctSeed__Recurring_Billing__c(
            Name = 'MergeBillingTest',
            AcctSeed__Customer__c = acct.Id,
            AcctSeed__Billing_Frequency__c = 'Monthly',
            AcctSeed__Next_Billing_Date__c = Date.today().addDays(1),
            AcctSeed__Status__c = 'Active'
        );
        insert billing;

        MergeBillingExtension ext = new MergeBillingExtension(new ApexPages.StandardController(opp));
        System.assertEquals(1, ext.recurringBillings.size());
        ext.mergeOppWithSelectedRecurringBilling();
        ext.recurringBillings[0].selected = true;
        ext.mergeOppWithSelectedRecurringBilling();

        AcctSeed__Recurring_Billing_Line__c[] lines = [SELECT AcctSeed__Quantity__c, AcctSeed__Rate__c, AcctSeed__Product__c FROM AcctSeed__Recurring_Billing_Line__c WHERE AcctSeed__Recurring_Billing__c = :billing.Id];
        System.assertEquals(1, lines.size());
        System.assertEquals(42, lines[0].AcctSeed__Quantity__c);
        System.assertEquals(10, lines[0].AcctSeed__Rate__c);
        System.assertEquals(prod.Id, lines[0].AcctSeed__Product__c);

        ext = new MergeBillingExtension(new ApexPages.StandardController(opp));
        System.assertEquals(1, ext.recurringBillings[0].lines.size());
    }
}