unpackaged/main/default/objects/Account/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts (Account Executive)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <infoMessage>If you do not see the branch you expect, then clear the search dialog and click GO. All branches should appear for selection.  Or Manually type Dallas, Austin, San Antonio, Atlanta, or Pittsburgh</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in filtered look ups to limit the selection of inactive projects.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in filtered lookups to eliminate inactive and completed projects from selection.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/AcctSeed__Recurring_Billing__c.object-meta.xml
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <formula>AcctSeed__Customer__r.Account_Executive__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Executive</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Customer__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Billings</relationshipLabel>
    <relationshipName>Recurring_Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/AcctSeed__Recurring_Billing_Line__c.object-meta.xml
<CustomObject>
    <description>Defines the line level detail of a recurring billing. Aggregation of recurring billing lines constitute a recurring billing.</description>
    <label>Recurring Billing Line</label>
    <nameField>
        <displayFormat>RBL-{00000}</displayFormat>
        <label>Recurring Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <formula>AcctSeed__Recurring_Billing__r.Account_Executive__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Executive</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeed__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Quantity__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Rate__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Rate__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Recurring_Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Recurring_Billing__c</fullName>
    <label>Recurring Billing</label>
    <referenceTo>AcctSeed__Recurring_Billing__c</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>Account.Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <displayFormat>C-{0}</displayFormat>
    <label>Opportunity/Contract Number</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/AcctSeed__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project_Task__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeed__Project__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/GA_Billing_Group__c.field-meta.xml
<CustomField>
    <fullName>GA_Billing_Group__c</fullName>
    <label>GA Billing Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/GA_Billing_Group__c.field-meta.xml
<CustomField>
    <fullName>GA_Billing_Group__c</fullName>
    <label>GA Billing Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carrier Access Services</fullName>
            </value>
            <value>
                <fullName>Infrastructure-as-a-Service</fullName>
            </value>
            <value>
                <fullName>SIP Trunking, Calling Plans, DID and Toll Free Numbers</fullName>
            </value>
            <value>
                <fullName>Data Center Services</fullName>
            </value>
            <value>
                <fullName>IT Services</fullName>
            </value>
            <value>
                <fullName>Customer Premise Equipment</fullName>
            </value>
            <value>
                <fullName>Taxes, Surcharges and Fees</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Support Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MergeBillingExtension.cls
/*
Controller for Opportunity Billing merge page

02/14/15 BS@IC Created(00127964)
11/11/16 KW@IC added opportunityid to recurring billing line creation (line 93)
*/

public class MergeBillingExtension {
    private Opportunity opp;
    public OliWrapper[] olis {get; set;}
    public RecurringBillingWrapper[] recurringBillings {get; set;}

    public MergeBillingExtension(ApexPages.StandardController ctrl) {
        //Get Opportunity details
        if(!Test.isRunningTest())
            ctrl.addFields(new String[]{'AccountId', 'Contract_Number__c', 'Account.Branch__c', 'Account.Account_Executive__c'});
        opp = (Opportunity)ctrl.getRecord();

        //Get Opportunity line items
        olis = new OliWrapper[]{};
        Set<String> oliFields = new Set<String> {'Quantity', 'UnitPrice', 'Discount', 'Product2Id', 'Product2.AcctSeed__Revenue_GL_Account__c', 'AcctSeed__Project__c', 'AcctSeed__Project_Task__c', 'GA_Billing_Group__c', 'Description'};
        for(FieldSetMember member : SObjectType.OpportunityLineItem.fieldsets.Merge_Billing_Fields.getFields())
            oliFields.add(member.getFieldPath());
        for(OpportunityLineItem oli : Database.query(
            'SELECT ' + String.join(new List<String>(oliFields), ', ') + ' ' +
            'FROM OpportunityLineItem ' +
            'WHERE OpportunityId = \'' + opp.Id + '\' ' +
            'LIMIT 1000'
        )) {
            olis.add(new OliWrapper(oli));
        }

        //Get Recurring Billing fields to be queried
        Set<String> recurringBillingFields = new Set<String>{'Id'}; //Query requires at least 1 field
        for(FieldSetMember fsm : SObjectType.AcctSeed__Recurring_Billing__c.fieldsets.Merge_Billing_Fields.getFields())
            recurringBillingFields.add(fsm.getFieldPath());

        //Query Recurring Billings
        Set<Id> billingIds = new Set<Id>();
        recurringBillings = new RecurringBillingWrapper[]{};
        for(AcctSeed__Recurring_Billing__c billing : Database.query('SELECT ' + String.join(new List<String>(recurringBillingFields), ', ') + ' FROM AcctSeed__Recurring_Billing__c WHERE AcctSeed__Status__c = \'Active\' AND AcctSeed__Customer__c = \'' + opp.AccountId + '\' LIMIT 1000')) {
            billingIds.add(billing.Id);
            recurringBillings.add(new RecurringBillingWrapper(billing));
        }

        //Ger Recurring Billing Line fields to be queried
        Set<String> recurringBillingLineFields = new Set<String>{'AcctSeed__Recurring_Billing__c'};
        for(FieldSetMember fsm : SObjectType.AcctSeed__Recurring_Billing_Line__c.fieldsets.Merge_Billing_Fields.getFields())
            recurringBillingLineFields.add(fsm.getFieldPath());

        //Query Recurring Billing Lines
        Map<Id, AcctSeed__Recurring_Billing_Line__c[]> linesByBillingId = new Map<Id, AcctSeed__Recurring_Billing_Line__c[]>();
        for(AcctSeed__Recurring_Billing_Line__c line : Database.query('SELECT ' + String.join(new List<String>(recurringBillingLineFields), ', ') + ' FROM AcctSeed__Recurring_Billing_Line__c WHERE AcctSeed__Recurring_Billing__c IN :billingIds LIMIT 10000')) {
            if(!linesByBillingId.containsKey(line.AcctSeed__Recurring_Billing__c))
                linesByBillingId.put(line.AcctSeed__Recurring_Billing__c, new AcctSeed__Recurring_Billing_Line__c[]{});

            linesByBillingId.get(line.AcctSeed__Recurring_Billing__c).add(line);
        }

        //Populate lines associated with each recurring billing
        for(RecurringBillingWrapper wrapper : recurringBillings)
            if(linesByBillingId.containsKey(wrapper.billing.Id))
                wrapper.lines = linesByBillingId.get(wrapper.billing.Id);
    }

    public PageReference mergeOppWithSelectedRecurringBilling() {
        //Get selected recurring billing
        RecurringBillingWrapper selected = null;
        for(RecurringBillingWrapper wrapper : recurringBillings)
            if(wrapper.selected == true) {
                selected = wrapper;
                break;
            }

        //Error if nothing is selected
        if(selected == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You must select a Recurring Billing'));
            return null;
        }

        Boolean lineSelected = false;
        AcctSeed__Recurring_Billing_Line__c[] toInsert = new AcctSeed__Recurring_Billing_Line__c[]{};
        for(OliWrapper line : olis) {
            if(line.selected == true) {
                lineSelected = true;
                
                toInsert.add(new AcctSeed__Recurring_Billing_Line__c(
                    AcctSeed__Recurring_Billing__c = selected.billing.Id,
                    AcctSeed__Quantity__c = line.oli.Quantity,
                    AcctSeed__Rate__c = line.oli.UnitPrice * (line.oli.Discount != null ? (100 - line.oli.Discount) / 100 : 1),
                    AcctSeed__Product__c = line.oli.Product2Id,
                    AcctSeed__Revenue_GL_Account__c = line.oli.Product2.AcctSeed__Revenue_GL_Account__c,
                    Opportunity__c=opp.id,
                    AcctSeed__Project__c = line.oli.AcctSeed__Project__c,
                    AcctSeed__Project_Task__c = line.oli.AcctSeed__Project_Task__c,
                    Opportunity_Contract_Number__c = opp.Contract_Number__c,
                    Billing_Category__c = line.oli.GA_Billing_Group__c,
                    RB_Invoice_Line_Description__c = line.oli.Description,
                    Taxable__c = true,
                    AcctSeed__GL_Account_Variable_1__c = opp.AccountId != null ? opp.Account.Branch__c : null,
                    AcctSeed__GL_Account_Variable_2__c = opp.AccountId != null ? opp.Account.Account_Executive__c : null
                ));
            }
        }

        //Error if no Opportunity Line Item is selected
        if(lineSelected == false) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You must select an Opportunity Product'));
            return null;
        }

        SavePoint sp = Database.setSavePoint();
        try {
            insert toInsert;
            return new PageReference('/' + opp.Id);
        }
        catch(DmlException e) {
            for(Integer i = 0, l = e.getNumDml(); i < l; i++)
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getDmlMessage(i)));
            Database.rollback(sp);
            return null;
        }
    }

    public class OliWrapper {
        public Boolean selected {get; set;}
        public OpportunityLineItem oli {get; set;}
        
        public OliWrapper(OpportunityLineItem line) {
            selected = true;
            oli = line;
        }
    }

    public class RecurringBillingWrapper {
        public Boolean selected {get; set;}
        public AcctSeed__Recurring_Billing__c billing {get; set;}
        public AcctSeed__Recurring_Billing_Line__c[] lines {get; set;}

        public RecurringBillingWrapper(AcctSeed__Recurring_Billing__c rb) {
            selected = false;
            billing = rb;
            lines = new AcctSeed__Recurring_Billing_Line__c[]{};
        }
    }
}