unpackaged/main/default/objects/Account/fields/AcctSeed__Accounting_Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Type__c</fullName>
    <inlineHelpText>Used in filtered lookups for Accounts Payable and Billing screens to limit selection of Accounts to those marked as Customers or Vendors for use by Accounting.</inlineHelpText>
    <label>Accounting Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Customer and Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/AcctSeed__GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts (GL Variable 1)</relationshipLabel>
    <relationshipName>AccountsGLAV1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/AcctSeed__Account_Payable__c.object-meta.xml
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Payee_Reference__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payee_Reference__c</fullName>
    <inlineHelpText>Used for Vendor Invoice Number or Expense processing date if account payable is generated from expenses.</inlineHelpText>
    <label>Payee Reference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Only populate if the entire bill is related to one client account.</inlineHelpText>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Accounts_Payable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable_Line__c/AcctSeed__Account_Payable_Line__c.object-meta.xml
<CustomObject>
    <description>Line item expense associated with an payable. The aggregation of multiple payable lines constitute a payable record.</description>
    <label>Payable Line</label>
    <nameField>
        <displayFormat>APL-{00000}</displayFormat>
        <label>Payable Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payable Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/AcctSeed__Account_Payable__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account_Payable__c</fullName>
    <inlineHelpText>Reference to Accounts Payable Header.</inlineHelpText>
    <label>Payable</label>
    <referenceTo>AcctSeed__Account_Payable__c</referenceTo>
    <relationshipName>Project_Account_Payable_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/AcctSeed__Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Amount__c</fullName>
    <inlineHelpText>Currency field to record amount of line.</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/AcctSeed__GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 1</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Accounting Variable must have a Type of "GL Account Variable 1".</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Payable Lines (GL Variable 1)</relationshipLabel>
    <relationshipName>Account_Payable_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/AcctSeed__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Account_Payable_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/Billing_Line__c.field-meta.xml
<CustomField>
    <fullName>Billing_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Billing Line</label>
    <referenceTo>AcctSeed__Billing_Line__c</referenceTo>
    <relationshipName>Account_Payable_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>equals</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing__c/AcctSeed__Billing__c.object-meta.xml
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Customer__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The organization you would like to pay you for your product or service. This is a filtered lookup to the Account where Accounting Status equals "Customer" or "Customer and Vendor".</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/AcctSeed__Billing_Line__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing__c</fullName>
    <inlineHelpText>Reference to parent object.</inlineHelpText>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Project_Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Billing Lines (GL Account Variable 1)</relationshipLabel>
    <relationshipName>Billing_Lines2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to Salesforce Products. Drives GL Revenue Account if selected and no Revenue GL Account is selected in the Billing Line. Also drives GL Account Variables on transaction line if no Project Task is selected on the Billing Line.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Upon posting a credit entry will be made to this GL Account and a corresponding debit entry will be made to the AR Control Account set in the Accounting Settings Tab.</inlineHelpText>
    <label>Revenue GL Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/AcctSeed__Accounting_Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Type__c</fullName>
    <label>Tax Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Taxable Product</fullName>
            </value>
            <value>
                <fullName>Tax Exempt Product</fullName>
            </value>
            <value>
                <fullName>Tax Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/AcctSeed__GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Variable 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CreateBillingLinesUtil.cls
/*
    Purpose: When a Billing is Created and is related to a recurring billing record, pass through Account Payable Lines should be captured as billing lines.

    10/12/2015  MD@IC  Initial creation (00121705)
*/
public class CreateBillingLinesUtil{

    public static void createLines(Map<Id, AcctSeed__Billing__c> billingMap){
        BillingLineSalesTaxTriggerUtil.bulkNote = true;
        BillingLineSalesTaxTriggerUtil.run = false;
        System.debug('[MD] start');
     
        List<AcctSeed__Billing_Line__c> billingLinesToInsert = new List<AcctSeed__Billing_Line__c>();
        // get all customer Ids - so you can query the AP lines
        Map<Id, List<AcctSeed__Account_Payable_Line__c>> customerIdToAPLines = new Map<Id, List<AcctSeed__Account_Payable_Line__c>>();
        Set<Id> customers = new Set<Id>();
        for(AcctSeed__Billing__c b : billingMap.values()){
            customers.add(b.AcctSeed__Customer__c);
            customerIdToAPLines.put(b.AcctSeed__Customer__c, new List<AcctSeed__Account_Payable_Line__c>());
        }

        // QUery all Account Payable Lines where Billable is True, APLine.Client = Billing.Customer and APLine.BillingLine is blank and APLine.Parent_Status is posted
        List<AcctSeed__Account_Payable_Line__c> apLines = [SELECT Id, AcctSeed__Account_Payable__r.AcctSeed__Payee_Reference__c, AcctSeed__Product__r.AcctSeed__Accounting_Type__c, AcctSeed__Product__r.Name, Client__c, AcctSeed__Quantity__c, AcctSeed__Amount__c, AcctSeed__Product__c, AcctSeed__Product__r.AcctSeed__Revenue_GL_Account__c, AcctSeed__GL_Account_Variable_1__c, AcctSeed__GL_Account_Variable_2__c
                                                           FROM AcctSeed__Account_Payable_Line__c 
                                                           WHERE AcctSeed__Billable__c = true
                                                             AND AcctSeed__Parent_Status__c = 'Posted' 
                                                             AND Client__c IN :customers 
                                                             AND Billing_Line__c = ''];
        for(AcctSeed__Account_Payable_Line__c l : apLines){
            customerIdToAPLines.get(l.Client__c).add(l);
        }

        System.debug('[MD] apLines = ' + apLines);

        // Create a Billing Line for each AP LIne:
        // Billing Line Quantity = AP Line Quantity (if blank or 0, make =1)
        // Product = Product
        // Billing Line Rate = APLine.Total                                     <-- ?
        // Billing Line Revenue GL = Product.Revenue GL                         <-- Product should also be required
        // Billing Line Accounting Variable 1 = AP Line Accounting Variable 1   <--| AcctSeed__Accounting_Variable__c
        // Billing Line Accounting Variable 2 = AP Line Accounting Variable 2   <--|

        List<AcctSeed__Account_Payable_Line__c> apLinesToUpdate = new List<AcctSeed__Account_Payable_Line__c>();
        List<Product2> passThroughProduct = [SELECT Id, AcctSeed__Revenue_GL_Account__c FROM Product2 WHERE PassThrough_Taxes__c = true];

        // for each billing record
        for(AcctSeed__Billing__c b : billingMap.values()){
            // for each apl related to the customer
            for(AcctSeed__Account_Payable_Line__c apl : customerIdToAPLines.get(b.AcctSeed__Customer__c)){
                // check for the required fields
                if(String.isNotBlank(apl.AcctSeed__Product__c) && String.isNotBlank(apl.AcctSeed__Product__r.AcctSeed__Revenue_GL_Account__c)){
                    // && String.isNotBlank(apl.AcctSeed__Total__c)
                    AcctSeed__Billing_Line__c l = new AcctSeed__Billing_Line__c(
                        AcctSeed__Billing__c = b.Id,
                        AcctSeed__Hours_Units__c = (String.isBlank(String.valueOf(apl.AcctSeed__Quantity__c)) || apl.AcctSeed__Quantity__c == 0 ? 1 : apl.AcctSeed__Quantity__c),
                        AcctSeed__Product__c = apl.AcctSeed__Product__c,
                        //AcctSeed__Rate__c = apl.Total,
                        AcctSeed__Rate__c = apl.AcctSeed__Amount__c,
                        AcctSeed__Revenue_GL_Account__c = apl.AcctSeed__Product__r.AcctSeed__Revenue_GL_Account__c,
                        AcctSeed__GL_Account_Variable_1__c = apl.AcctSeed__GL_Account_Variable_1__c,
                        AcctSeed__GL_Account_Variable_2__c = apl.AcctSeed__GL_Account_Variable_2__c,
                        RB_Invoice_Line_Description__c = apl.AcctSeed__Product__r.Name + ' / ' + apl.AcctSeed__Account_Payable__r.AcctSeed__Payee_Reference__c
                    );
                    if(apl.AcctSeed__Product__r.AcctSeed__Accounting_Type__c == 'Tax Rate'){
                        l.AcctSeed__Product__c = passThroughProduct[0].Id;
                        l.AcctSeed__Revenue_GL_Account__c = passThroughProduct[0].AcctSeed__Revenue_GL_Account__c;
                    }
                    billingLinesToInsert.add(l);
                    apLinesToUpdate.add(apl);
                }
            }
        }
        
        System.debug('[MD] billingLinesToInsert = ' + billingLinesToInsert);

        System.debug('[MD] billing lines = ' + billingLinesToInsert.size());
        System.debug('[MD] ap lines = ' + apLinesToUpdate.size());
        

        if(!billingLinesToInsert.isEmpty()){
            BillingLineSalesTaxTriggerUtil.run = false;
            BillingLineSalesTaxTriggerUtil.bulkNote = true;
            insert billingLinesToInsert;
            System.debug('[MD] post insert: ' + billingLinesToInsert[0].Id);
            // Update the AP Line. Billing Line lookup
            for(Integer i = 0; i < billingLinesToInsert.size(); i++)
                apLinesToUpdate[i].Billing_Line__c = billingLinesToInsert[i].Id;
             
            Set<AcctSeed__Account_Payable_Line__c> apSet = new Set<AcctSeed__Account_Payable_Line__c>();
            apSet.addAll(apLinesToUpdate);
            List<AcctSeed__Account_Payable_Line__c> newApList = new List<AcctSeed__Account_Payable_Line__c>();
            for(AcctSeed__Account_Payable_Line__c a : apSet){
                newApList.add(a);
            }
            update newApList;
            System.debug('[MD] post update: ' + apLinesToUpdate[0].Billing_Line__c);
        }
    }
}