unpackaged/main/default/objects/Account/fields/AcctSeed__GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts (GL Variable 1)</relationshipLabel>
    <relationshipName>AccountsGLAV1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AcctSeed__GL_Account_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts (GL Variable 2)</relationshipLabel>
    <relationshipName>AccountsGLAV2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AcctSeed__GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts (GL Variable 3)</relationshipLabel>
    <relationshipName>AccountsGLAV3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <infoMessage>If you do not see the branch you expect, then clear the search dialog and click GO. All branches should appear for selection.  Or Manually type Dallas, Austin, San Antonio, Atlanta, or Pittsburgh</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing__c/AcctSeed__Billing__c.object-meta.xml
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Customer__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The organization you would like to pay you for your product or service. This is a filtered lookup to the Account where Accounting Status equals "Customer" or "Customer and Vendor".</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in approvals of billing records and therefore related detail lines. A value of "Posted" indicates the record is final and a debit and credit line have been entered into the transaction object for each billing line.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Credit_Memo__c/AcctSeed__Billing_Credit_Memo__c.object-meta.xml
<CustomObject>
    <description>Used to document the relationship a billing credit memo record and a billing invoice record. A billing credit memo record is created during the apply credit memo process.</description>
    <label>Billing Credit Memo</label>
    <nameField>
        <displayFormat>BCM-{00000}</displayFormat>
        <label>Billing Credit Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Billing_Credit_Memo__c/fields/AcctSeed__Billing_Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing_Credit_Memo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Memo</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The type field of the billing must be "Credit Memo"</errorMessage>
        <filterItems>
            <field>AcctSeed__Billing__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Credit Memo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Applied Invoices to Credit Memo</relationshipLabel>
    <relationshipName>Billing_Credit_Memos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Credit_Memo__c/fields/AcctSeed__Billing_Invoice__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing_Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The type field of the billing must be "Invoice"</errorMessage>
        <filterItems>
            <field>AcctSeed__Billing__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Invoice</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Applied Credit Memos to Invoice</relationshipLabel>
    <relationshipName>Billing_Credit_Memos1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/AcctSeed__Billing_Line__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing__c</fullName>
    <inlineHelpText>Reference to parent object.</inlineHelpText>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Project_Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Billing Lines (GL Account Variable 1)</relationshipLabel>
    <relationshipName>Billing_Lines2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__GL_Account_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Billing Lines (GL Account Variable 2)</relationshipLabel>
    <relationshipName>Billing_Lines3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Billing Lines (GL Account Variable 3)</relationshipLabel>
    <relationshipName>Billing_Lines4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Hours_Units__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Hours_Units__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Quantity for Product Pricing, Hours for Service pricing.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Rate__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Rate__c</fullName>
    <inlineHelpText>Product or Service Rate. Up to 6 decimal places.</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/CreateCreditMemosTest.cls
/*
    10/05/15    SB @ IC    00119955
    07/12/16    BS @ IC    Modified for compatibility with Accounting Seed update (132907)
*/
@isTest
public class CreateCreditMemosTest {
    
    @isTest
    public static void testController() {
        AccountingSeedUnitTestUtility.initAccountingSeed();
        
        Account acct = new Account(Name = 'Test Account',Branch__c = AccountingSeedUnittestUtility.variables[0].Id);
        insert acct;
        
        AcctSeed__Billing__c billing = new AcctSeed__Billing__c(AcctSeed__Customer__c = acct.Id);
        insert billing;
        
        AcctSeed__Billing_Line__c line1 = new AcctSeed__Billing_Line__c(
            AcctSeed__Billing__c = billing.Id,
            AcctSeed__Rate__c = 10,
            AcctSeed__Hours_Units__c = 40,
            AcctSeed__GL_Account_Variable_1__c = AccountingSeedUnitTestUtility.variables[0].Id,
            AcctSeed__GL_Account_Variable_2__c = AccountingSeedUnitTestUtility.variables[2].Id,
            AcctSeed__GL_Account_Variable_3__c = AccountingSeedUnitTestUtility.variables[4].Id
        );
        AcctSeed__Billing_Line__c line2 = new AcctSeed__Billing_Line__c(
            AcctSeed__Billing__c = billing.Id,
            AcctSeed__Rate__c = 10,
            AcctSeed__Hours_Units__c = 40,
            AcctSeed__GL_Account_Variable_1__c = AccountingSeedUnitTestUtility.variables[0].Id,
            AcctSeed__GL_Account_Variable_2__c = AccountingSeedUnitTestUtility.variables[2].Id,
            AcctSeed__GL_Account_Variable_3__c = AccountingSeedUnitTestUtility.variables[4].Id
        );
        insert new list<AcctSeed__Billing_Line__c>{line1,line2};
        
        CreateCreditMemosController control = new CreateCreditMemosController(new ApexPages.StandardController(billing));
        control.billingLines[0].selected = true;
        control.billingLines[0].creditQuantity = 50;
        System.assertEquals(null,control.saveCreditMemos());
        
        control.billingLines[0].creditQuantity = 40;
        control.billingLines[1].selected = true;
        control.billingLines[1].overrideAmount = true;
        control.billingLines[1].creditQuantity = 1;
        control.billingLines[1].creditAmount = 200;
        
        Id memoId = control.saveCreditMemos().getUrl().substringAfterLast('/');
        
        //BS@IC Can no longer post billings directly
        /* AcctSeed__Billing__c memo = [SELECT AcctSeed__Status__c FROM AcctSeed__Billing__c WHERE Id = :memoId];
        memo.AcctSeed__Status__c = 'Posted';
        update memo; */
        AcctSeed.PostResult[] postResult = AcctSeed.BillingPostService.postBillings(new AcctSeed__Billing__c[]{new AcctSeed__Billing__c(Id = memoId)});
        System.assertEquals(true, postResult[0].isSuccess);
        
        System.assertEquals(1, [SELECT Id FROM AcctSeed__Billing_Credit_Memo__c WHERE AcctSeed__Billing_Invoice__c = :billing.Id AND AcctSeed__Billing_Credit_Memo__c = :memoId].size());
    }
}