unpackaged/main/default/objects/Account/fields/AcctSeed__Billing_Format__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used to configure formatting and display of fields in Billing PDF. Overrides the default Billing Format defined in Accounting Settings.</inlineHelpText>
    <label>Billing Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Billing</value>
        </filterItems>
        <infoMessage>The Type must equal "Billing"</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
    <relationshipLabel>Accounts (Billing Format)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Accounting_Settings__c/AcctSeed__Accounting_Settings__c.object-meta.xml
<CustomObject>
    <description>Main record used to define configuration and default settings used in the application.</description>
    <label>Accounting Settings</label>
    <nameField>
        <label>Account Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Accounting_Settings__c/fields/AcctSeed__AP_Control_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__AP_Control_GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This should be set to the main Accounts Payable GL Account.</inlineHelpText>
    <label>AP Control GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Accounting_Settings (AP Control GL Account)</relationshipLabel>
    <relationshipName>PMA_Main1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Accounting_Settings__c/fields/AcctSeed__AR_Control_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__AR_Control_GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This should be set to the main Accounts Receivable GL Account.</inlineHelpText>
    <label>AR Control GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Accounting_Settings (AR Control GL Account)</relationshipLabel>
    <relationshipName>PMA_Main</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Accounting_Settings__c/fields/AcctSeed__Current_Year_Earnings_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Current_Year_Earnings_GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Gl Account used when creating current year earnings financial cube records</inlineHelpText>
    <label>Current Year Earnings GL Account</label>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Accounting_Settings (Current Year Earnings GL Account)</relationshipLabel>
    <relationshipName>Accounting_Settings9</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Accounting_Settings__c/fields/AcctSeed__Default_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Default_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the account that the majority of payments are made from and that deposits are made to. When entering a cash receipt it will default to this bank account. When creating a cash disbursement batch it will default to this account.</inlineHelpText>
    <label>Default Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Bank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Accounting_Settings (Default Bank Account)</relationshipLabel>
    <relationshipName>Accounting_Settings2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Accounting_Variable__c/AcctSeed__Accounting_Variable__c.object-meta.xml
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Accounting_Variable__c/fields/AcctSeed__Active__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Active allows for selection of the variable in several filtered lookups.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Accounting_Variable__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>Used to determine GL Account Variables 1-4 and Time Card Variables 1-2.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GL Account Variable 1</fullName>
            </value>
            <value>
                <fullName>GL Account Variable 2</fullName>
            </value>
            <value>
                <fullName>GL Account Variable 3</fullName>
            </value>
            <value>
                <fullName>GL Account Variable 4</fullName>
            </value>
            <value>
                <fullName>Time Card Variable 1</fullName>
            </value>
            <value>
                <fullName>Time Card Variable 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Format__c/AcctSeed__Billing_Format__c.object-meta.xml
<CustomObject>
    <description>Used to store configuration and default settings related to the pdf generation of a record.</description>
    <label>PDF Format</label>
    <nameField>
        <label>PDF Format Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Billing_Format__c/fields/AcctSeed__Default_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Default_Email_Template__c</fullName>
    <inlineHelpText>This is the email template used when emailing Billing PDF Invoices. Use the Template Unique Name NOT the Template Name when populating this field.</inlineHelpText>
    <label>Default Email Template</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Format__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>The type of record this PDF Format is associated.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Purchase Order</fullName>
            </value>
            <value>
                <fullName>Activity Statement</fullName>
            </value>
            <value>
                <fullName>Outstanding Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Billing_Format__c/fields/AcctSeed__Visualforce_PDF_Page__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Visualforce_PDF_Page__c</fullName>
    <inlineHelpText>The API name of the Visualforce page that is used to display the PDF rendition of the Billing.</inlineHelpText>
    <label>Visualforce PDF Page</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__GL_Account__c/AcctSeed__GL_Account__c.object-meta.xml
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <label>General Ledger Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Ledger Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Active__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Denotes if the GL Account is active. Most filtered lookups to the GL Account object look for an active status.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Bank__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Bank__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the GL Account is a Bank account and can be selected to record Cash Receipts, Cash Disbursements and use the Bank Reconciliation.</inlineHelpText>
    <label>Bank/Credit Card Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Sub_Type_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Sub_Type_1__c</fullName>
    <inlineHelpText>Used in conjunction with the Type field to further classify GL Accounts in reports. This pick list is dependent on Type.</inlineHelpText>
    <label>Sub Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AcctSeed__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Assets</fullName>
            </value>
            <value>
                <fullName>Cost of Goods Sold</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Liabilities</fullName>
            </value>
            <value>
                <fullName>Owners Equity</fullName>
            </value>
            <value>
                <fullName>Product Revenue</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Service Revenue</fullName>
            </value>
            <value>
                <fullName>General &amp; Administrative</fullName>
            </value>
            <value>
                <fullName>Other Income</fullName>
            </value>
            <value>
                <fullName>Salaries &amp; Benefits</fullName>
            </value>
            <value>
                <fullName>Legal &amp; Professional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>Denotes the major grouping for financial reporting.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Balance Sheet</fullName>
                <default>true</default>
                <label>Balance Sheet</label>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__GL_Account__c/fields/GL_Number__c.field-meta.xml
<CustomField>
    <fullName>GL_Number__c</fullName>
    <externalId>true</externalId>
    <label>GL Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Ledger__c/AcctSeed__Ledger__c.object-meta.xml
<CustomObject>
    <description>Used to associate and aggregate financial transaction or budget entries with a specific entity.</description>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Ledger__c/fields/AcctSeed__Default_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Default_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the account that the majority of payments are made from and that deposits are made to. When entering a cash receipt it will default to this bank account. When creating a cash disbursement batch it will default to this account.</inlineHelpText>
    <label>Default Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only GL Accounts with Bank checked are allowed.</errorMessage>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Bank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Default_Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Ledger__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Budget</fullName>
                <default>true</default>
                <label>Budget</label>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AccountingSeedUnitTestUtility.cls
/*
    02/05/15    SB @ IC
    09/16/15    BS @ IC Static GL Accounts (119334)
*/
public class AccountingSeedUnitTestUtility {
    
    public static AcctSeed__Accounting_Settings__c settings;
    public static list<AcctSeed__Accounting_Variable__c> variables;
    public static Product2 prod;
    public static AcctSeed__GL_Account__c revenueGL;
    public static AcctSeed__GL_Account__c bankGL;
    public static AcctSeed__GL_Account__c retainedGL;
    public static AcctSeed__GL_Account__c receivablesGL;
    public static AcctSeed__GL_Account__c cashGL;
    public static AcctSeed__GL_Account__c payableGL;
    
    public static void initAccountingSeed() {
        revenueGL = new AcctSeed__GL_Account__c(
            AcctSeed__Type__c = 'Revenue',
            AcctSeed__Active__c = true,
            Name = 'Unassigned Revenue',
            GL_Number__c = '40000'
        );
        
        bankGL = new AcctSeed__GL_Account__c(
            AcctSeed__Type__c = 'Balance Sheet',
            AcctSeed__Sub_Type_1__c = 'Assets',
            AcctSeed__Active__c = true,
            AcctSeed__Bank__c = true,
            Name = 'Default Bank GL',
            GL_Number__c = '10120'
        );
        
        retainedGL = new AcctSeed__GL_Account__c(
            AcctSeed__Type__c = 'Balance Sheet',
            AcctSeed__Sub_Type_1__c = 'Assets',
            AcctSeed__Active__c = true,
            Name = 'Retained Earnings',
            GL_Number__c = '39000'
        );
        
        receivablesGL = new AcctSeed__GL_Account__c(
            AcctSeed__Type__c = 'Balance Sheet',
            AcctSeed__Sub_Type_1__c = 'Assets',
            AcctSeed__Active__c = true,
            Name = 'Unassigned Receivables',
            GL_Number__c = '11100'
        );
        
        cashGL = new AcctSeed__GL_Account__c(
            AcctSeed__Type__c = 'Balance Sheet',
            AcctSeed__Sub_Type_1__c = 'Assets',
            AcctSeed__Active__c = true,
            Name = 'Cash - Clearing Account',
            GL_Number__c = '10190'
        );
        
        payableGL = new AcctSeed__GL_Account__c(
            AcctSeed__Type__c = 'Balance Sheet',
            AcctSeed__Sub_Type_1__c = 'Assets',
            AcctSeed__Active__c = true,
            Name = 'Accounts Payable - Vendors',
            GL_Number__c = '20010'
        );
        
        insert new list<AcctSeed__GL_Account__c>{revenueGL,bankGL,retainedGL,receivablesGL,cashGL,payableGL};
        
        AcctSeed__Ledger__c ledger = new AcctSeed__Ledger__c(
            Name = 'ledger',
            AcctSeed__Type__c = 'Transactional'
        );
        insert ledger;
        
        AcctSeed__Billing_Format__c format = new AcctSeed__Billing_Format__c(
            AcctSeed__Default_Email_Template__c = 'Billing_Email_Template',
            AcctSeed__Visualforce_PDF_Page__c = 'ProjectBillingPDF'
        );
        insert format;
        
        settings = new AcctSeed__Accounting_Settings__c(
            AcctSeed__AP_Control_GL_Account__c = payableGL.Id,
            AcctSeed__AR_Control_GL_Account__c = receivablesGL.Id,
            AcctSeed__Current_Year_Earnings_GL_Account__c = retainedGL.Id,
            AcctSeed__Default_Bank_Account__c = bankGL.Id,
            AcctSeed__Retained_Earnings_GL_Account__c = retainedGL.Id,
            AcctSeed__Revenue_GL_Account__c = revenueGL.Id,
            AcctSeed__Unapplied_Cash_GL_Account__c = cashGL.Id,
            AcctSeed__Default_Ledger__c = ledger.Id,
            AcctSeed__Default_Billing_Format__c = format.Id,
            AcctSeed__Billing_Outstanding_Statement_Format__c = format.Id,
            AcctSeed__Billing_Activity_Statement_Format__c = format.Id
        );
        insert settings;
        
        variables = new list<AcctSeed__Accounting_Variable__c>{};
        
        AcctSeed__Accounting_Variable__c variable11 = new AcctSeed__Accounting_Variable__c(
            AcctSeed__Type__c = 'GL Account Variable 1'
        );
        variables.add(variable11);
        
        AcctSeed__Accounting_Variable__c variable12 = new AcctSeed__Accounting_Variable__c(
            AcctSeed__Type__c = 'GL Account Variable 1'
        );
        variables.add(variable12);
        
        AcctSeed__Accounting_Variable__c variable21 = new AcctSeed__Accounting_Variable__c(
            AcctSeed__Type__c = 'GL Account Variable 2'
        );
        variables.add(variable21);
        
        AcctSeed__Accounting_Variable__c variable22 = new AcctSeed__Accounting_Variable__c(
            AcctSeed__Type__c = 'GL Account Variable 2'
        );
        variables.add(variable22);
        
        AcctSeed__Accounting_Variable__c variable31 = new AcctSeed__Accounting_Variable__c(
            AcctSeed__Type__c = 'GL Account Variable 3'
        );
        variables.add(variable31);
        
        AcctSeed__Accounting_Variable__c variable32 = new AcctSeed__Accounting_Variable__c(
            AcctSeed__Type__c = 'GL Account Variable 3'
        );
        variables.add(variable32);
        
        insert variables;
        
        AcctSeed__Accounting_Period__c acctPeriod = new AcctSeed__Accounting_Period__c(
            Name = System.now().format('yyyy-MM'),
            AcctSeed__Start_Date__c = Date.today().addDays(-7),
            AcctSeed__End_Date__c = Date.today(),
            AcctSeed__Status__c = 'Open'
        );
        insert acctPeriod;
        
        prod = new Product2(
            IsActive = true,
            Name = 'Test Product',
            ProductCode = '12345',
            AcctSeed__Revenue_GL_Account__c = revenueGL.Id,
            AcctSeed__GL_Account_Variable_1__c = variable11.Id,
            AcctSeed__GL_Account_Variable_2__c = variable21.Id,
            AcctSeed__GL_Account_Variable_3__c = variable31.Id
        );
        insert prod;
    }
}