unpackaged/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <infoMessage>If you do not see the branch you expect, then clear the search dialog and click GO. All branches should appear for selection.  Or Manually type Dallas, Austin, San Antonio, Atlanta, or Pittsburgh</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/AcctSeed__Recurring_Billing__c.object-meta.xml
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Customer__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Billings</relationshipLabel>
    <relationshipName>Recurring_Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Recurring Billings</relationshipLabel>
    <relationshipName>Recurring_Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/AcctSeed__Recurring_Billing_Line__c.object-meta.xml
<CustomObject>
    <description>Defines the line level detail of a recurring billing. Aggregation of recurring billing lines constitute a recurring billing.</description>
    <label>Recurring Billing Line</label>
    <nameField>
        <displayFormat>RBL-{00000}</displayFormat>
        <label>Recurring Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Quantity__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Rate__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Rate__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Recurring_Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Recurring_Billing__c</fullName>
    <label>Recurring Billing</label>
    <referenceTo>AcctSeed__Recurring_Billing__c</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/Manually_Edit_RB_Line_Description__c.field-meta.xml
<CustomField>
    <fullName>Manually_Edit_RB_Line_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manually Edit RB Line Description</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used in Process Builder, set when Recurring Billing Line is created</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/Lease_Rates__c.object-meta.xml
<CustomObject>
    <label>Lease Rates</label>
    <nameField>
        <label>Lease Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_1__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_1__c</fullName>
    <label>GA Rate 1</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_1_Dollar_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_1_Dollar_Threshold__c</fullName>
    <label>GA Rate 1 Dollar Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_1_Payment_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_1_Payment_Threshold__c</fullName>
    <label>GA Rate 1 Payment Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_2__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_2__c</fullName>
    <label>GA Rate 2</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_2_Dollar_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_2_Dollar_Threshold__c</fullName>
    <label>GA Rate 2 Dollar Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_2_Payment_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_2_Payment_Threshold__c</fullName>
    <label>GA Rate 2 Payment Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_3__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_3__c</fullName>
    <label>GA Rate 3</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_3_Dollar_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_3_Dollar_Threshold__c</fullName>
    <label>GA Rate 3 Dollar Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/GA_Rate_3_Payment_Threshold__c.field-meta.xml
<CustomField>
    <fullName>GA_Rate_3_Payment_Threshold__c</fullName>
    <label>GA Rate 3 Payment Threshold</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/Rate_Markup__c.field-meta.xml
<CustomField>
    <fullName>Rate_Markup__c</fullName>
    <label>Rate Markup</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lease_Rates__c/fields/TSB_Rate__c.field-meta.xml
<CustomField>
    <fullName>TSB_Rate__c</fullName>
    <label>TSB Rate</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AnyWare_Term_2016__c.field-meta.xml
<CustomField>
    <fullName>AnyWare_Term_2016__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is a required field. If unsure, set to 60.</description>
    <inlineHelpText>Select the appropriate AnyWare Term/Rate</inlineHelpText>
    <label>AnyWare Term</label>
    <referenceTo>Lease_Rates__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>Account.Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OPS_Category__c.field-meta.xml
<CustomField>
    <fullName>OPS_Category__c</fullName>
    <label>OPS Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
                <color>#009900</color>
                <label>INSTALLATION</label>
            </value>
            <value>
                <fullName>ICN</fullName>
                <color>#3366FF</color>
                <label>ICN</label>
            </value>
            <value>
                <fullName>MAC</fullName>
                <color>#FF6600</color>
                <label>MAC</label>
            </value>
            <value>
                <fullName>RECAST</fullName>
                <color>#000099</color>
                <label>RECAST</label>
            </value>
            <value>
                <fullName>Post Installation</fullName>
                <color>#000000</color>
                <label>POST INSTALLATION</label>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TSP_Disc_Percent__c.field-meta.xml
<CustomField>
    <fullName>TSP_Disc_Percent__c</fullName>
    <label>TSP Promotional Discount %</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/classes/RecurringBillingLineTest.cls
/*
    Unit test for RecurringBillingLineTrigger and RecurringBillingLineHandler.
*/
@isTest
public class RecurringBillingLineTest {
    
    @isTest
    public static void testOpportunityLookup() {
        AccountingSeedUnitTestUtility.initAccountingSeed();
        
        Account acct = new Account(Name = 'Test',Branch__c = AccountingSeedUnitTestUtility.variables[0].Id);
        insert acct;
        
        Lease_Rates__c rate = new Lease_Rates__c(
            Name = '60',
            Rate_Markup__c = 1.05000,
            TSB_Rate__c = 0.02102,
            GA_Rate_1__c = 1,
            GA_Rate_1_Dollar_Threshold__c = 1,
            GA_Rate_1_Payment_Threshold__c = 1,
            GA_Rate_2__c = 1,
            GA_Rate_2_Dollar_Threshold__c = 1,
            GA_Rate_2_Payment_Threshold__c = 1,
            GA_Rate_3__c = 1,
            GA_Rate_3_Dollar_Threshold__c = 1,
            GA_Rate_3_Payment_Threshold__c = 1
        );
        insert rate;
        
        Opportunity opp = new Opportunity(
            AccountId = acct.Id,
            Name = 'Test',
            CloseDate = Date.today(),
            StageName = 'Prospecting',
            AnyWare_Term_2016__c = rate.Id,
            OPS_Category__c = 'Installation',
            TSP_Disc_Percent__c = 0
        );
        insert opp;
        
        AcctSeed__Recurring_Billing__c billing = new AcctSeed__Recurring_Billing__c(
            Name = 'Test',
            AcctSeed__Customer__c = acct.Id,
            AcctSeed__Opportunity__c = opp.Id,
            AcctSeed__Billing_Frequency__c = 'Monthly',
            AcctSeed__Next_Billing_Date__c = Date.today()
        );
        insert billing;
        
        AcctSeed__Recurring_Billing_Line__c line = new AcctSeed__Recurring_Billing_Line__c(
            AcctSeed__Recurring_Billing__c = billing.Id,
            AcctSeed__Quantity__c = 1,
            AcctSeed__Rate__c = 1,
            AcctSeed__Revenue_GL_Account__c = AccountingSeedUnitTestUtility.revenueGL.Id,
            Manually_Edit_RB_Line_Description__c = true
        );
        insert line;
        
        line = [SELECT Opportunity__c FROM AcctSeed__Recurring_Billing_Line__c WHERE Id = :line.Id];
        System.assertEquals(opp.Id,line.Opportunity__c);
    }
}