unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/AcctSeed__Recurring_Billing__c.object-meta.xml
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing__c/fields/AcctSeed__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Recurring Billings</relationshipLabel>
    <relationshipName>Recurring_Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/AcctSeed__Recurring_Billing_Line__c.object-meta.xml
<CustomObject>
    <description>Defines the line level detail of a recurring billing. Aggregation of recurring billing lines constitute a recurring billing.</description>
    <label>Recurring Billing Line</label>
    <nameField>
        <displayFormat>RBL-{00000}</displayFormat>
        <label>Recurring Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/AcctSeed__Recurring_Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Recurring_Billing__c</fullName>
    <label>Recurring Billing</label>
    <referenceTo>AcctSeed__Recurring_Billing__c</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Recurring_Billing_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used in Process Builder, set when Recurring Billing Line is created</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Recurring Billing Lines</relationshipLabel>
    <relationshipName>Recurring_Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/RecurringBillingLineHandler.cls
/*
    Utility class for RecurringBillingLineTrigger
    
    03/15/17    SB @ IC    00145429 Populates opportunity lookup from recurring billing
*/
public class RecurringBillingLineHandler {
    
    public static void updateOpportunityLookup(list<AcctSeed__Recurring_Billing_Line__c> lines) {
        map<Id,Id> billingOppMap = new map<Id,Id>{};
        for (AcctSeed__Recurring_Billing_Line__c line : lines) {
            billingOppMap.put(line.AcctSeed__Recurring_Billing__c,null);
        }
        
        for (AcctSeed__Recurring_Billing__c billing : [SELECT AcctSeed__Opportunity__c FROM AcctSeed__Recurring_Billing__c WHERE Id IN :billingOppMap.keySet()]) {
            billingOppMap.put(billing.Id,billing.AcctSeed__Opportunity__c);
        }
        
        for (AcctSeed__Recurring_Billing_Line__c line : lines) {
            line.Opportunity__c = billingOppMap.get(line.AcctSeed__Recurring_Billing__c);
        }
    }
}