unpackaged/main/default/objects/AcctSeed__Account_Payable__c/AcctSeed__Account_Payable__c.object-meta.xml
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Discount_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The amount taken as a discount in the cash disbursements cycle if the invoice is paid within the number of days specified in the discount days field from the Invoice date.</inlineHelpText>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Net_Amount__c</fullName>
    <formula>AcctSeed__Total__c - AcctSeed__Discount_Amount__c - IF(AcctSeed__Reverse_Charge__c,AcctSeed__Purchase_Tax3__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Invoice Total minus Discount Amount.</inlineHelpText>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Payee__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payee__c</fullName>
    <formula>IF( NOT(ISBLANK(AcctSeed__Vendor__c)) , AcctSeed__Vendor__r.Name, 
IF( NOT(ISBLANK(AcctSeed__Contact__c)) ,  AcctSeed__Contact__r.FirstName &amp; " "  &amp; AcctSeed__Contact__r.LastName,  
IF( NOT(ISBLANK(AcctSeed__Employee__c)) ,   AcctSeed__Employee__r.FirstName &amp; " "  &amp; AcctSeed__Employee__r.LastName,  
"" )))</formula>
    <inlineHelpText>Formula field that lists either the vendor, contact or the employee as the Payee. Used in reporting and as a convenient reference to the source record for the Payee.</inlineHelpText>
    <label>Payee</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Payee_Reference__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payee_Reference__c</fullName>
    <inlineHelpText>Used for Vendor Invoice Number or Expense processing date if account payable is generated from expenses.</inlineHelpText>
    <label>Payee Reference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <formula>IF(AcctSeed__Total__c &lt; 0,"Credit Memo", "Invoice")</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Automatically determined by the sum of the Accounts Payable Lines. If total Accounts Payable lines are negative the document is a Credit Memo. If Positive then it is an Invoice.</inlineHelpText>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Vendor__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>An Account Payable can have either the Account (Vendor), Contact or User (Employee) as the Payee.  One object must be chosen.</inlineHelpText>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Vendor, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Accounts Filtered on Accounting Type=Vendor and Accounting Active=True</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Project_Payable_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__AP_Disbursement__c/AcctSeed__AP_Disbursement__c.object-meta.xml
<CustomObject>
    <description>Used to document the relationship an payable has with a cash disbursement.</description>
    <label>AP Disbursement</label>
    <nameField>
        <displayFormat>APD-{00000}</displayFormat>
        <label>AP Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__AP_Disbursement__c/fields/AcctSeed__Account_Payable__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account_Payable__c</fullName>
    <label>Payable</label>
    <referenceTo>AcctSeed__Account_Payable__c</referenceTo>
    <relationshipLabel>Applied Cash Disbursements</relationshipLabel>
    <relationshipName>Account_Payable_Cash_Disbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__AP_Disbursement__c/fields/AcctSeed__Account_Payable_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account_Payable_Date__c</fullName>
    <formula>AcctSeed__Account_Payable__r.AcctSeed__Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payable Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__AP_Disbursement__c/fields/AcctSeed__Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Discount_Amount__c</fullName>
    <formula>IF( AcctSeed__Paid_Amount__c  &gt; 0, AcctSeed__Account_Payable__r.AcctSeed__Discount_Amount__c, AcctSeed__Account_Payable__r.AcctSeed__Discount_Amount__c *-1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__AP_Disbursement__c/fields/AcctSeed__Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Net_Amount__c</fullName>
    <formula>AcctSeed__Account_Payable__r.AcctSeed__Net_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__AP_Disbursement__c/fields/AcctSeed__Payable_Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payable_Amount__c</fullName>
    <formula>AcctSeed__Account_Payable__r.AcctSeed__Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/AcctSeed__Cash_Disbursement__c.object-meta.xml
<CustomObject>
    <description>Used to document the payment made to an outside vendor, contact, or employee typically recorded as an payable. The aggregation of multiple cash disbursements constitute a cash disbursement batch.</description>
    <label>Cash Disbursement</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>Cash Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Amount__c</fullName>
    <inlineHelpText>The amount of money to be disbursed.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Amount_in_Words__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Amount_in_Words__c</fullName>
    <label>Amount In Words</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Upon posting a credit entry will be made to this account and a corresponding debit entry will be made to the AP Control account set in the Accounting Settings Tab.</inlineHelpText>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Bank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Cash Disbursements</relationshipLabel>
    <relationshipName>Cash_Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Check_Number__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Check_Number__c</fullName>
    <label>Check Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Disbursement_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <inlineHelpText>The Date in which the Cash Disbursement was made.</inlineHelpText>
    <label>Disbursement Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Payee__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payee__c</fullName>
    <formula>IF( NOT(ISBLANK(AcctSeed__Alternate_Payee_Name__c)), AcctSeed__Alternate_Payee_Name__c,
IF( NOT(ISBLANK(AcctSeed__Vendor__c)) , AcctSeed__Vendor__r.Name,
IF( NOT(ISBLANK(AcctSeed__Contact__c)) , AcctSeed__Contact__r.FirstName &amp; " " &amp; AcctSeed__Contact__r.LastName, 
IF( NOT(ISBLANK(AcctSeed__Employee__c)) , AcctSeed__Employee__r.FirstName &amp; " " &amp; AcctSeed__Employee__r.LastName, 
"" ))))</formula>
    <inlineHelpText>Formula field that lists either the vendor, contact or the employee as the Payee. Used in reporting and as a convenient reference to the source record for the Payee.</inlineHelpText>
    <label>Payee</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Payee_City_State_Zip__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payee_City_State_Zip__c</fullName>
    <formula>IF(NOT(ISBLANK(AcctSeed__Payee_City__c)) &amp;&amp; NOT(ISBLANK(AcctSeed__Payee_State__c)), AcctSeed__Payee_City__c &amp; " " &amp; AcctSeed__Payee_State__c &amp; IF(NOT(ISBLANK(AcctSeed__Payee_Postal_Code__c)), " " &amp; AcctSeed__Payee_Postal_Code__c, ""),
IF(NOT(ISBLANK(AcctSeed__Vendor__c)), AcctSeed__Vendor__r.BillingCity &amp; " " &amp; AcctSeed__Vendor__r.BillingState &amp; " " &amp; AcctSeed__Vendor__r.BillingPostalCode,
IF(NOT(ISBLANK(AcctSeed__Contact__c)), AcctSeed__Contact__r.MailingCity &amp; " " &amp; AcctSeed__Contact__r.MailingState &amp; " " &amp; AcctSeed__Contact__r.MailingPostalCode,
IF(NOT(ISBLANK(AcctSeed__Employee__c)), AcctSeed__Employee__r.City &amp; " " &amp; AcctSeed__Employee__r.State &amp; " " &amp; AcctSeed__Employee__r.PostalCode, 
""))))</formula>
    <label>Payee City State Zip</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Payee_Country__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payee_Country__c</fullName>
    <formula>IF(NOT(ISBLANK(AcctSeed__Payee_Country2__c)), AcctSeed__Payee_Country2__c,
IF(NOT(ISBLANK(AcctSeed__Vendor__c)), AcctSeed__Vendor__r.BillingCountry,
IF(NOT(ISBLANK(AcctSeed__Contact__c)),AcctSeed__Contact__r.MailingCountry,
IF(NOT(ISBLANK(AcctSeed__Employee__c)),AcctSeed__Employee__r.Country,
""))))</formula>
    <label>Payee Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Payee_Street__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payee_Street__c</fullName>
    <formula>IF(NOT(ISBLANK(AcctSeed__Payee_Street2__c)), AcctSeed__Payee_Street2__c,
IF(NOT(ISBLANK(AcctSeed__Vendor__c)), AcctSeed__Vendor__r.BillingStreet,
IF(NOT(ISBLANK(AcctSeed__Contact__c)), AcctSeed__Contact__r.MailingStreet,
IF(NOT(ISBLANK(AcctSeed__Employee__c)), AcctSeed__Employee__r.Street,
""))))</formula>
    <label>Payee Street</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Reference__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Reference__c</fullName>
    <inlineHelpText>Represents Check number for traditional paper checks or a payment reference provided by your bank if it is electronic.</inlineHelpText>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>Denotes the method in which the disbursement was made. Check indicated traditional paper check. Electronic would be used to represent ACH, Wires or any other form of electronic payment.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Vendor__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>A Cash Disbursement can have either the Account (Vendor), Contact or User (Employee) as the Payee. One object must be chosen.</inlineHelpText>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Vendor, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cash Disbursements</relationshipLabel>
    <relationshipName>Cash_Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/iProPrintchecksComponent.cls
public with sharing class iProPrintchecksComponent {
    public List<AcctSeed__Cash_Disbursement__c> cashDisbursements {get; private set;}
    public Id cashDisbursementBatchId;
    public Id cashDisbursementId;
    
    public Id getCashDisbursementBatchId() {
        return cashDisbursementBatchId;
    }
    
    public void setCashDisbursementBatchId(Id cashDisbursementBatchId) {
        this.cashDisbursementBatchId = cashDisbursementBatchId; 
          init();
    }

    public Id getCashDisbursementId() {
        return cashDisbursementId;
    }
    
    public void setCashDisbursementId(Id cashDisbursementId) {
        this.cashDisbursementId = cashDisbursementId;   
          init();
    }
        
    private void init() {
        cashDisbursements = new List<AcctSeed__Cash_Disbursement__c>();
        if (cashDisbursementBatchId != null) {
            cashDisbursements = [Select Id,Name,AcctSeed__Payee__c,AcctSeed__Payee_Street__c,AcctSeed__Payee_City_State_Zip__c,
            AcctSeed__Payee_Country__c,AcctSeed__Check_Number__c,AcctSeed__Type__c,AcctSeed__Reference__c,AcctSeed__Amount__c,AcctSeed__Amount_In_Words__c,AcctSeed__Disbursement_Date__c,
            AcctSeed__Bank_Account__c,
                (Select Id,Name,AcctSeed__Account_Payable__c,AcctSeed__Account_Payable_Date__c,
                  AcctSeed__Payable_Amount__c,AcctSeed__Payee_Reference__c,
                  AcctSeed__Net_Amount__c,AcctSeed__Discount_Amount__c,
                  AcctSeed__Account_payable__r.AcctSeed__Type__c,
                  AcctSeed__Account_Payable__r.Name,AcctSeed__Account_Payable__r.AcctSeed__Vendor__c,
                  AcctSeed__Account_Payable__r.AcctSeed__Date__c,            
                  AcctSeed__Account_Payable__r.AcctSeed__Discount_Amount__c,
                  AcctSeed__Account_Payable__r.AcctSeed__Net_Amount__c,
                  AcctSeed__Paid_Amount__c
                    From AcctSeed__Account_Payable_Cash_Disbursements__r 
                    Order By Name)
                    From AcctSeed__Cash_Disbursement__c
                    Where AcctSeed__Cash_Disbursement_Batch__c = :cashDisbursementBatchId order by AcctSeed__Check_Number__c limit 500];
                                
        }
        else if (cashDisbursementId != null) {
            cashDisbursements = [Select Id,Name,AcctSeed__Payee__c,AcctSeed__Payee_Street__c,AcctSeed__Payee_City_State_Zip__c,
            AcctSeed__Payee_Country__c,AcctSeed__Check_Number__c,AcctSeed__Reference__c,AcctSeed__Type__c,AcctSeed__Amount__c,AcctSeed__Amount_In_Words__c,AcctSeed__Disbursement_Date__c,
            AcctSeed__Bank_Account__c,
                (Select Id,Name,AcctSeed__Account_Payable__c,AcctSeed__Account_Payable_Date__c,
                  AcctSeed__Payable_Amount__c,AcctSeed__Payee_Reference__c,
                  AcctSeed__Net_Amount__c,AcctSeed__Discount_Amount__c,
                  AcctSeed__Account_payable__r.AcctSeed__Type__c,
                  AcctSeed__Account_Payable__r.Name,AcctSeed__Account_Payable__r.AcctSeed__Vendor__c,
                  AcctSeed__Account_Payable__r.AcctSeed__Date__c,            
                  AcctSeed__Account_Payable__r.AcctSeed__Discount_Amount__c,
                  AcctSeed__Account_Payable__r.AcctSeed__Net_Amount__c,
                  AcctSeed__Paid_Amount__c
                    From AcctSeed__Account_Payable_Cash_Disbursements__r 
                    Order By Name)
                    From AcctSeed__Cash_Disbursement__c
                    Where Id = :cashDisbursementId]; 
                    
        }
    }                 
}